### PR TITLE
Add ES serviceaccount to jenkins

### LINKED ISSUE #68: Configure ES serviceaccount
```
$ oc adm policy add-role-to-user view -z elasticsearch
$ oc env statefulset/elasticsearch NAMESPACE=`oc project -q`
```

Without this ES nodes do not know about each other. e.g. some node has data some not.

### PR DESCRIPTION
**Pull request by pavolloffay**
Fixes #68 

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Looks like jenkins didn't like it.

**Comment by pavolloffay** [comment]
Yes there is a problem with permissions, I am figuring it out.

**Comment by pavolloffay** [comment]
I have run `oc adm policy add-role-to-user admin system:serviceaccount:jaeger-test:jenkins` to solve permissions with command `oc adm policy add-role-to-user view -z elasticsearch` run by jenkins. Note this adds admin permission for the `jaeger-test` project, so keep in mind when doing #62

**Comment by pavolloffay** [comment]
I will merge, as this is the root cause of failing tests in other PRs

**Pull request merged**
