### PR TITLE
Add instructions on how into the service catalog

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

This is how the service catalog looks like after this PR

image

### CODE REVIEW

**Comment by yurishkuro** [comment]
why is the tool using Go logo instead of Jaeger logo?

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/artwork

**Comment by jpkrohling** [comment]
Mostly because that's the closest we get :) All we can do with the template is to refer to a CSS class and there's no class (yet?) for Jaeger there.

**Comment by jpkrohling** [comment]
Created https://github.com/openshift/openshift-logos-icon/issues/21

**Pull request merged**
