### PR TITLE
Fix for issue 55, update test to create edge route and test using it

### PR DESCRIPTION
**Pull request by kevinearls**
Signed-off-by: Kevin Earls <kearls@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
Thanks @kevinearls, now it's worth to define it in a separate file. Do you want to do it? If not I will create a PR after this is in.

**Comment by kevinearls** [comment]
@pavolloffay Sorry I don't understand what you mean by a separate file.  Do you mean a separate Jenkinsfile?  If so I'd be happy to create one.

**Comment by pavolloffay** [comment]
Could you please push the branch into this repo and open a new PR? The reason is #62

**Comment by kevinearls** [comment]
@pavolloffay I don't have access rights to create a branch in this repo.  Can you give them to me?

**Comment by pavolloffay** [comment]
done

**Comment by pavolloffay** [comment]
closed in favour of https://github.com/jaegertracing/jaeger-openshift/pull/66

**Pull request closed without merging**
