### PR TITLE
Update template to add deployment and test with ElasticSearch

### PR DESCRIPTION
**Pull request by kevinearls**

### CODE REVIEW

**Comment by pavolloffay** [comment]
should jenkins report the status here?

**Comment by kevinearls** [comment]
@pavolloffay Yes it should.  I have this job running on the new CNCF CI Jenkins but it looks like there's something wrong with the credentials.  I'll try to resolve it this afternoon.

**Comment by pavolloffay** [comment]
it's green! @kevinearls ready to merge?

**Comment by kevinearls** [comment]
@pavolloffay yes, please go ahead and merge this.

**Pull request merged**
