### PR TITLE
Update to use new SPAN_STORAGE env var

### PR DESCRIPTION
**Pull request by objectiser**
Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by objectiser** [comment]
Will need retesting once jenkins is back online. @kevinearls if you could let me know when to trigger, thanks.

**Comment by objectiser** [comment]
@pavolloffay I've tested this locally against elasticsearch and it all starts up fine. So think it can be merged.

@kevinearls Might be good if you could confirm works?

**Comment by kevinearls** [comment]
@objectiser Sure, will confirm on Monday

**Comment by objectiser** [comment]
@kevinearls ok thanks, I'll merge for now but feel free to create an issue if any problem found.

**Comment by kevinearls** [comment]
@objectiser  I have run both the performance tests and a version of the template tests using both Cassandra and ElasticSearch, and everything is working correctly.

**Pull request merged**
