### PR TITLE
Adding storage definition for elasticsearch with deployment configuration

### PR DESCRIPTION
**Pull request by ofirattia**
## Which problem is this PR solving?
- No problem, enhancement for production deployment configurations

## Short description of the changes
- Added storage definition for elasticsearch on OpenShift
- Added elasticsearch deployment configuration with persistent volume

### CODE REVIEW

**Comment by ofirattia** [comment]
Travis is failing on license header checks and the header exists in both files.

**Comment by jpkrohling** [comment]
Could you please run `mvn license:format`, to get the headers fixed? The problem might be that we are in 2019 and the headers are for 2018.

**Review by pavolloffay — CHANGES_REQUESTED** [review]
@ofirattia thanks for the PR.

We do not want to support storage deployments in this repository and rather defer on well tested solutionns out there - e.g. elasticsearch from pires or helm charts. 

The elasticsaarch template what is in this repository is only for "try it out" purpose. I am not even sure if the ES is configured with the right discovery (the same for your deployment)

**Comment by ofirattia** [comment]
> @ofirattia thanks for the PR.
> 
> We do not want to support storage deployments in this repository and rather defer on well tested solutionns out there - e.g. elasticsearch from pires or helm charts.
> 
> The elasticsaarch template what is in this repository is only for "try it out" purpose. I am not even sure if the ES is configured with the right discovery (the same for your deployment)


thanks for your quick reply, actually I tested it with 120 instances on our cluster, I am not sure if it will be used in the same configuration for production, but for performance tests and user acceptance for sure. I found it useful.

Anyway, its seems that there is no recommended approach for production and its kind of do it your own.

do you want to add the storage configuration as example in the README or what you have now its enough from your side?

**Comment by pavolloffay** [comment]
> do you want to add the storage configuration as example in the README or what you have now its enough from your side?

I think it's enough what we have. I believe similar examples can be found in k8s docs.

**Comment by ofirattia** [comment]
Thanks, Closed.

**Comment by jpkrohling** [comment]
@ofirattia in any case, thanks for your PR! I'd be really interested in hearing more about your tests: 

> actually I tested it with 120 instances on our cluster

Are you able to provide more info? Feel free to ping me via Gitter or IRC.

**Pull request closed without merging**
