### PR TITLE
Replaced the underlying Cassandra image

### LINKED ISSUE #11: Use a proper Cassandra docker image
For the moment, we are using the Cassandra docker image under my own namespace. We should decide which image to use: Docker Hub's? Our own, based on GCE's (kubernetes official example)? Another one?

### PR DESCRIPTION
**Pull request by jpkrohling**
fixes #11 #19

### CODE REVIEW

**Comment by jpkrohling** [comment]
Blocked by: uber/jaeger#278 . This won't work until the image `jaegertracing/jaeger-cassandra-schema` is published with those changes.

**Comment by yurishkuro** [comment]
@jpkrohling 278 is merged, but do you need a tagged release here?

**Comment by jpkrohling** [comment]
In theory, no, because each commit reaching master should push a new image to DockerHub and it becomes available as "latest": https://hub.docker.com/r/jaegertracing/jaeger-cassandra-schema/tags/

But as Travis is not running, it's not publishing new builds. So, I'd either need permissions to push to the `jaegertracing`, or will need someone to locally build the image and push it to DockerHub. Or, better yet, fix Travis, but as this might take longer.

**Comment by pavolloffay** [comment]
But will it be a proper tag? Like `0.5.0` we would like to use this tag in templates

**Comment by jpkrohling** [comment]
The tag in the template is another task. For this task, it's not needed, as the template defaults to `latest`. So, as long as the image is available under `latest`, this PR will work.

**Comment by pavolloffay** [comment]
Yes, but If I would use this with `0.5.x` it wouldn't and that is the only working tag, so we should consider including it here or in a new tag (0.5.1)?

**Comment by jpkrohling** [comment]
I'm confused now :) @yurishkuro , were you asking if this repo needs a new tagged version, or were you asking if I need a new tagged version of the Docker image at DockerHub?

**Comment by yurishkuro** [comment]
I released 0.5.2, the images should be published shortly

**Comment by jpkrohling** [comment]
The version 0.5.2 is published, but the `latest` reference hasn't been updated. Would you please set `latest` tag to point to this version?

**Comment by yurishkuro** [comment]
We probably need to update the upload script, since `latest` has been replaced with the version tag. Perhaps we shouldn't be pushing `latest` at all? You can use `0.5`, which will be "latest for 0.5.x"

**Comment by jpkrohling** [comment]
For this PR, I'll use 0.5, and we can later discuss how to move forward. For the record: I prefer a `latest` to exist.

**Comment by jpkrohling** [comment]
@pavolloffay I think this is now ready to be merged.

**Comment by pavolloffay** [comment]
LGTM, but I haven't run it (only k8s version). If you need manual tests I would prefer that our QE should be responsible for this.

**Comment by objectiser** [comment]
@jpkrohling There is no tag 0.5 for the all-in-one docker image :( Either need to revert the all-in-one template back to using `latest` or the docker image needs to be tagged.

**Pull request merged**
