### PR TITLE
Add support for zipkin port

### PR DESCRIPTION
**Pull request by objectiser**
I've included a test - but this only gets used with the all-in-one template. I'll create a card to get the QE tests updated to test both templates - although ideally we need to get them moved into this repo.

### CODE REVIEW

**Comment by objectiser** [comment]
:red_circle: Jenkins CI Build`#1`: Console log: [external](https://paste.fedoraproject.org/paste/dIPEqi55sjd4vNgf7n2~2g), [internal](https://jenkins-jaeger-ci.cloud2.jonqe.lab.eng.bos.redhat.com/job/jaegertracing-ci/job/jaeger-openshift/job/PR-38/1/display/redirect)

**Comment by objectiser** [comment]
There seems to be a problem with the zipkin port on jaeger-collector in the production template - works in the all-in-one - investigating.

**Comment by jpkrohling** [comment]
[Test new Docker images (from scratch)](https://trello.com/c/6JYerRnW/66-test-new-docker-images-from-scratch)

**Comment by jpkrohling** [comment]
LGTM once the CI tests are passing.

**Comment by objectiser** [comment]
:red_circle: Jenkins CI Build`#2`: Console log: [external](https://paste.fedoraproject.org/paste/9uKAbRouUVcKcCu8c3qvHA), [internal](https://jenkins-jaeger-ci.cloud2.jonqe.lab.eng.bos.redhat.com/job/jaegertracing-ci/job/jaeger-openshift/job/PR-38/2/display/redirect)

**Comment by objectiser** [comment]
@jpkrohling Any thoughts on this failure - it is failing to connect to the jaeger-collector port 9411 - however the same test in all-in-one works. The port is defined in the collector Service and collector-pod Deployment. Any ideas?

**Comment by objectiser** [comment]
:white_check_mark: Jenkins CI Build`#3`: Console log: [external](https://paste.fedoraproject.org/paste/v078Fjt5E1aIE62u7EpB9w), [internal](https://jenkins-jaeger-ci.cloud2.jonqe.lab.eng.bos.redhat.com/job/jaegertracing-ci/job/jaeger-openshift/job/PR-38/3/display/redirect)

**Comment by objectiser** [comment]
@jpkrohling @pavolloffay Thanks!

**Pull request merged**
