### PR TITLE
Cassandra nodetool drain

### PR DESCRIPTION
**Pull request by pavolloffay**
Similar to https://github.com/jaegertracing/jaeger-kubernetes/pull/21

### CODE REVIEW

**Comment by pavolloffay** [comment]
@jkandasa or @kevinearls could you please verify this?

**Comment by jpkrohling** [comment]
It looks fine, but I'd feel more comfortable with a positive confirmation from @jkandasa or @kearls , specially because the continuous integration test has failed.

@jkandasa , @kearls , it would be nice to test this with 3 Cassandra pods, create some data (spans), scale down one Cassandra, check that no data is missing, then scale down again, and check again that no data is missing.

@pavolloffay , did you run it locally ?

**Comment by jpkrohling** [comment]
Looks like the continuous integration has passed while I was writing the comment above O_o

**Comment by jkandasa** [comment]
@pavolloffay @jpkrohling Jenkins-CI has some permission issue, i fixed it. as follows. and works as expected.
image

**Comment by pavolloffay** [comment]
@jpkrohling no only k8s version, I defer this to CI or QE team

**Comment by jkandasa** [comment]
@jpkrohling @pavolloffay Couple of notes on scaling Cassandra node test with production template from this PR.
* I cannot do scaling on GUI of openshift for Cassandra pod. No option available for `Scale up` and `Scale down`. on template do we need to specify `minReplicas:3` in the place of `replicas:3`?
image
* I did terminate a `cassandra-0` pod manually. Terminated pod recovered/up automatically in few minutes. Jaeger query works as expected. 
* After 30 minutes from the above operation, I did terminate `cassandra-1` pod. Terminated pod recovered/up automatically in few minutes. Jaeger query throws the following exception,
```
GET https://jaeger-query-jaeger-ci.cloud2.jonqe.lab.eng.bos.redhat.com/api/traces?end=1501143745321000&limit=20&lookback=1h&maxDuration&minDuration&service=from-automation&start=1501140145320000
{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":500,"msg":"Cannot achieve consistency level ONE"}]}
```
* from this point jeager-production server goes to **not usable state**.
```
NAME                                   READY     STATUS      RESTARTS   AGE
po/cassandra-0                         1/1       Running     0          57m
po/cassandra-1                         1/1       Running     0          19m
po/cassandra-2                         1/1       Running     1          1h
```

**Comment by pavolloffay** [comment]
> Jaeger query throws the following exception

did the exception disappear after some time?

**Comment by jkandasa** [comment]
@pavolloffay Just now I checked throws the same exception.
Cassandra pod status when I check this:
```
NAME                                   READY     STATUS      RESTARTS   AGE
po/cassandra-0                         1/1       Running     0          1h
po/cassandra-1                         1/1       Running     0          34m
po/cassandra-2                         1/1       Running     1          1h
```

**Comment by pavolloffay** [comment]
I think it's not related to this PR, but it's related to master and replication factor

**Comment by pavolloffay** [comment]
@jkandasa could you please do the same with master/head?

**Comment by jkandasa** [comment]
@pavolloffay I see this issue on `master/head` too. 
```
NAME                                   READY     STATUS      RESTARTS   AGE
po/cassandra-0                         1/1       Running     0          57m
po/cassandra-1                         1/1       Running     0          12m
po/cassandra-2                         1/1       Running     2          1h
```

**Comment by pavolloffay** [comment]
@jkandasa thanks. That issue is not related to this change. I think we can merge this and handle that separately.

**Pull request merged**
