### PR TITLE
Changed deployment verification command on jenkinsCI

### PR DESCRIPTION
**Pull request by jkandasa**

### CODE REVIEW

**Comment by jkandasa** [comment]
@objectiser JenkinsCI won't take the change from this PR. It will keep old `jenkins-ci/Jenkinsfile`. Here are the conditions on JenkinsCI configuration,

image

**Comment by objectiser** [comment]
@jkandasa So what do you suggest? Do we have to merge and hope it fixes the issue?

Is there a better solution - i.e. can the jenkinsfile just be configured in the jenkins job rather than having it as part of the git repo? If so - might be better solution as we may want the same pipeline triggered from multpile repos anyway.

**Comment by jkandasa** [comment]
@objectiser 
> Is there a better solution - i.e. can the jenkinsfile just be configured in the jenkins job rather than having it as part of the git repo? If so - might be better solution as we may want the same pipeline triggered from multpile repos anyway.

We can configure this file(`Jenkinsfile`) on Jenkins server itself. In this case, we have to maintain this file separately. When we have this file a part of the repository, If we lose our Jenkins server. We can setup another server with in a minute. And more features are here >> https://jenkins.io/doc/book/pipeline-as-code/

For this PR, I switched to **Trust** `Everyone` and triggered test. and switched back to Trust only `From users with Admin or Write permission`. So jenkins CI takes `Jenkinsfile` from PR and executed the job.

**Comment by jkandasa** [comment]
We can configure this file(`Jenkinsfile`) on Jenkins server itself. In this case, we have to maintain this file separately. When we have this file a part of the repository, If we lose our Jenkins server. We can setup another server with in a minute. And more features are here >> https://jenkins.io/doc/book/pipeline-as-code/

For this PR, I switched to **Trust** `Everyone` and triggered test. and switched back to Trust only `From users with Admin or Write permission`. So Jenkins CI takes `Jenkinsfile` from PR and executed the job.

**Comment by objectiser** [comment]
@jkandasa Thanks!

**Pull request merged**
